enum CampoSegOda {
  id,
  contrato,
  documentocompras,
  fechadocumento,
  proveedor,
  proyecto,
  // bdg2024,
  posicion,
  material,
  textobreve,
  unidadmedida,
  cantidaddepedido,
  // conformado,
  saldo,
  moneda,
  precioneto,
  valornetodepedido,
  subtotalcop,
  ivagastosnacionalizacion,
  factorivanac,
  valortotalcop,
  vrpagado,
  valoranticipo1,
  // nopdp,
  saldopendiente,
  fechadeentregaincoterm,
  // fechaconformidad,
  mesequipo,
  mesanticipos,
  gestor,
  // ou,
  // familia,
  incoterm,
  puerto,
  // wbe,
  observaciones1,
  observaciones2,
  // fechafirmadelcontratodecontrato,
  // fechafinalizacioncontrato,
  // fechaactadeinicio,
  // tiemposdetcadias,
  // tiemposdeentregadias,
  // fechaentregaoda,
  // fechaaprobaciondisenos,
  // hitodisenocumplido,
  // retiesino,
  // vigenciaretie,
  // fechatcacontractual,
  // fechaestimadatcacierremlm,
  // hitotcacumplido,
  // plandeproduccion,
  // fechapruebasqmlm,
  // hitopruebasqcumplido,
  // rollingtenderdeclarado,
  // rollingtenderno,
  // tiempoestimadodetransporte,
  fechaentregaincotermactualizada,
  // hitocumplido,
  tasa,
}
